- name: "system_02_file_system | Creating {{ LV_CONFIG }} volume"
  lvol:
      vg:  "{{ VG_Name }}"
      lv:  "{{ LV_CONFIG }}"
      size: "{{ LV_CONFIG_SIZE }}"
      force: yes

- name: "system_02_file_system | format {{ LV_CONFIG }} with the xfs filesystem"
  filesystem:
      fstype: "xfs"
      dev: "/dev/{{ VG_Name }}/{{ LV_CONFIG }}"

- name: "system_02_file_system | Create directory {{ LV_CONFIG_MNT }} if does not exist"
  file:
      path: "{{ LV_CONFIG_MNT }}"
      state: "directory"
      mode: '0755'

- name: "system_02_file_system | mount the lv {{ LV_CONFIG }} on {{ LV_CONFIG_MNT }}"
  mount:
      path: "{{ LV_CONFIG_MNT }}"
      src: "/dev/{{ VG_Name }}/{{ LV_CONFIG }}"
      fstype: "xfs"
      state: "mounted"