- name: "system_02_file_system | Creating {{ LV_CERTIFICATES }} volume"
  lvol:
      vg:  "{{ VG_Name }}" 
      lv:  "{{ LV_CERTIFICATES }}"
      size: "{{ LV_CERTIFICATES_SIZE }}"
      force: yes

- name: "system_02_file_system | format {{ LV_CERTIFICATES }} with the xfs filesystem"
  filesystem:
      fstype: "xfs"
      dev: "/dev/{{ VG_Name }}/{{ LV_CERTIFICATES }}"

- name: "system_02_file_system | Create directory {{ LV_CERTIFICATES_MNT }} if does not exist"
  file:
      path: "{{ LV_CERTIFICATES_MNT }}"
      state: "directory"
      mode: '0755'

- name: "system_02_file_system | mount the lv {{ LV_CERTIFICATES }} on {{ LV_CERTIFICATES_MNT }}"
  mount:
      path: "{{ LV_CERTIFICATES_MNT }}"
      src: "/dev/{{ VG_Name }}/{{ LV_CERTIFICATES }}"
      fstype: "xfs"
      state: "mounted"