- name: "system_02_file_system | Creating {{ LV_DOCKER }} volume"
  lvol:
      vg:  "{{ VG_Name }}" 
      lv:  "{{ LV_DOCKER }}"
      size: "{{ LV_DOCKER_SIZE }}"
      force: yes

- name: "system_02_file_system | format {{ LV_DOCKER }} with the xfs filesystem"
  filesystem:
      fstype: "xfs"
      dev: "/dev/{{ VG_Name }}/{{ LV_DOCKER }}"

- name: "system_02_file_system | Create directory {{ LV_DOCKER_MNT }} if does not exist"
  file:
      path: "{{ LV_DOCKER_MNT }}"
      state: "directory"
      mode: '0755'

- name: "system_02_file_system | mount the lv {{ LV_DOCKER }} on {{ LV_DOCKER_MNT }}"
  mount:
      path: "{{ LV_DOCKER_MNT }}"
      src: "/dev/{{ VG_Name }}/{{ LV_DOCKER }}"
      fstype: "xfs"
      state: "mounted"