- name: "system_02_file_system | Creating {{ LV_DATA }} volume"
  lvol:
      vg:  "{{ VG_Name }}" 
      lv:  "{{ LV_DATA }}"
      size: "{{ LV_DATA_SIZE }}"
      force: yes

- name: "system_02_file_system | format {{ LV_DATA }} with the xfs filesystem"
  filesystem:
      fstype: "xfs"
      dev: "/dev/{{ VG_Name }}/{{ LV_DATA }}"

- name: "system_02_file_system | Create directory {{ LV_DATA_MNT }} if does not exist"
  file:
      path: "{{ LV_DATA_MNT }}"
      state: "directory"
      mode: '0755'

- name: "system_02_file_system | mount the lv {{ LV_DATA }} on {{ LV_DATA_MNT }}"
  mount:
      path: "{{ LV_DATA_MNT }}"
      src: "/dev/{{ VG_Name }}/{{ LV_DATA }}"
      fstype: "xfs"
      state: "mounted"