- name: "system_02_file_system | Creating {{ LV_DATABASES }} volume"
  lvol:
      vg:  "{{ VG_Name }}" 
      lv:  "{{ LV_DATABASES }}"
      size: "{{ LV_DATABASES_SIZE }}"
      force: yes

- name: "system_02_file_system | format {{ LV_DATABASES }} with the xfs filesystem"
  filesystem:
      fstype: "xfs"
      dev: "/dev/{{ VG_Name }}/{{ LV_DATABASES }}"

- name: "system_02_file_system | Create directory {{ LV_DATABASES_MNT }} if does not exist"
  file:
      path: "{{ LV_DATABASES_MNT }}"
      state: "directory"
      mode: '0755'

- name: "system_02_file_system | mount the lv {{ LV_DATABASES }} on {{ LV_DATABASES_MNT }}"
  mount:
      path: "{{ LV_DATABASES_MNT }}"
      src: "/dev/{{ VG_Name }}/{{ LV_DATABASES }}"
      fstype: "xfs"
      state: "mounted"