- name: "system_02_file_system | Creating {{ LV_TMP }} volume"
  lvol:
      vg:  "{{ VG_Name }}" 
      lv:  "{{ LV_TMP }}"
      size: "{{ LV_TMP_SIZE }}"
      force: yes

- name: "system_02_file_system | format {{ LV_TMP }} with the xfs filesystem"
  filesystem:
      fstype: "xfs"
      dev: "/dev/{{ VG_Name }}/{{ LV_TMP }}"

- name: "system_02_file_system | Create directory {{ LV_TMP_MNT }} if does not exist"
  file:
      path: "{{ LV_TMP_MNT }}"
      state: "directory"
      mode: '0755'

- name: "system_02_file_system | mount the lv {{ LV_TMP }} on {{ LV_TMP_MNT }}"
  mount:
      path: "{{ LV_TMP_MNT }}"
      src: /dev/{{ VG_Name }}/{{ LV_TMP }}
      fstype: "xfs"
      state: "mounted"