- name: "system_02_file_system | Creating {{ LV_VAR }} volume"
  lvol:
      vg:  "{{ VG_Name }}"
      lv:  "{{ LV_VAR }}"
      size: "{{ LV_VAR_SIZE }}"
      force: yes

- name: "system_02_file_system | format {{ LV_VAR }} with the xfs filesystem"
  filesystem:
      fstype: "xfs"
      dev: "/dev/{{ VG_Name }}/{{ LV_VAR }}"

- name: "system_02_file_system | create temporary mount point : /mnt/var"
  file:
      path: "/mnt/var"
      state: "directory"
      mode: '0755'

- name: "system_02_file_system | mount the lv {{ LV_VAR }} on /mnt/var"
  mount:
      path: "/mnt/var"
      src: /dev/{{ VG_Name }}/{{ LV_VAR }}
      fstype: "xfs"
      state: "mounted"

- name: "system_02_file_system |Move originale {{ LV_VAR_MNT }} to {{ LV_VAR_MNT }}.old" 
  command: "cp -Rp /var/* /mnt/var/ "

